module.exports = Object.freeze({
  TIMELINE_STATUS_WAITING: 1,
  TIMELINE_STATUS_DOING: 0,
  TIMELINE_STATUS_DONE: 2,
  TIMELINE_TYPE_APP: 0,
  TIMELINE_TYPE_MODULE: 1,
  TIMELINE_ACTION_STATUS_UNFINISHED: 0,
  TIMELINE_ACTION_STATUS_FINISHED: 1,
  TIMELINE_ACTION_TYPE_USERSET: 0,
  TIMELINE_ACTION_TYPE_START: 1, // 开始
  TIMELINE_ACTION_TYPE_DEVELOP_FINISHED: 2, // 开发完成
  TIMELINE_ACTION_TYPE_TEST_FINISHED: 3, // 测试完成
  TIMELINE_ACTION_TYPE_SUBMIT: 4, // 对于APP是提交审核，对于模块是提交到APP
  TIMELINE_ACTION_TYPE_FINISH: 5, // 对于APP是 审核完成与其他处理彻底完成， 而对于模块是打prd版本。
  MODULE_TYPE_IOS: 'iOS',
  MODULE_TYPE_HTML: 'html',
  MODULE_TYPE_REACT: 'react',
  MODULE_GIT_TYPE_GITLAB: 'gitlab',
  MODULE_GIT_TYPE_GITHUB: 'github',
  JENKINS_BUILD_TYPE_MODULE_BUILD: 'module_build', // 目前平台上只跑两个jenkins任务，一个是模块打包
  JENKINS_BUILD_TYPE_MODULE_IMPORT: 'module_import', // 一个是模块接入管理
  JENKINS_JOB_BUILD_STATUS_BUILDING: 'BUILDING', // jenkins构建的状态
  JENKINS_JOB_BUILD_STATUS_SUCCESS: 'SUCCESS',
  JENKINS_JOB_BUILD_STATUS_UNSTABLE: 'UNSTABLE',
  JENKINS_JOB_BUILD_STATUS_FAILURE: 'FAILURE',
  JENKINS_JOB_BUILD_STATUS_ABORTED: 'ABORTED',
  MODULE_IMPORT_STATUS_WAITING: 0, // 模块接入管理的状态， 已提交，等待处理
  MODULE_IMPORT_STATUS_FAILED: 1, // jenkins接入失败。
  MODULE_IMPORT_STATUS_SUCCESS: 2, // 接入成功
  MODULE_IMPORT_STATUS_REJECT: 3 // 拒绝接入
})
